languageCode = "ja"
languageName = "Japanese"
# languageDirection = "ltr"
weight = 1

title = "IK base"
copyright = "&copy; 2024 IK"

[params]
  dateFormat = "2006/01/02"
  isoCode = "ja"
  displayName = ":flag-jp:"
  rtl = false
  # mainSections = ["section1", "section2"]
  description = "IKのサイト。"

[params.author]
  name = "IK"
  image = "img/author.png"
  headline = "セキュリティ専門家を目指す人"
  bio = "セキュリティ専門家を目指す人"
  links = [
     { github = "https://github.com/IK-20211125" },
     { x-twitter = "https://twitter.com/IK20240503" },
     { email = "https://ikbase.net/about" }
  ]
